const { existsSync } = require('fs')
const { join } = require('path')
const { spawn } = require('child_process')
const root = join(__dirname, '..')
const venv = join(root, '.venv', process.platform === 'win32' ? 'Scripts/python.exe' : 'bin/python')
const python = process.env.PYTHON || (existsSync(venv) ? venv : 'python')
const child = spawn(python, ['-B', '-m', 'uvicorn', 'main:app', '--reload', '--host', '127.0.0.1', '--port', '8000'], { cwd: join(root, 'backend'), stdio: 'inherit', windowsHide: true })
child.on('error', error => { console.error('无法启动后端，请先安装 Python 和 requirements.txt 依赖：', error.message); process.exitCode = 1 })
child.on('exit', code => { process.exitCode = code || 0 })
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, () => child.kill(signal))
